travis:
  secure:
    BINSTAR_TOKEN: tn1/mUDRLy5l8uh4kfyFukhBLH8dXQCaUxhx5U3IWBJOa5CY7y/S1/iTH6R6UGxW76cYAXXbJaKJ6EXnB6ite/+dBiPuq010j6dGE+VaKJGZhF7nPxGHUS7xa0Sa7LrJeu+FHGIi6IAm9eHEno0PhBpTCjM4kEsGFo2USoDSSuazd5TKpQSuPPCzNkd1dsg6BdRSONd0nnGFFMjohjCO/aPOT50JGDKXW8GU7VpSJ3bMlzjirJ2LFEVgzQVM7iug0jxz0chAdyEqPLrjrMQ8BRkppr2bKFFum26/haERA0x9cUp/R/UoXwK9puLo9ewLGFYMjC5vlFD58oAykVX2vw36BhJdw7IfY9hSp38LLybMx0UglYI3qvlbFDiyFCaMnSkNEKVRuQaxx8xtZAyZ7cxjFhEh3CRnYEgiV2FpMnDWtMrko/DKjZxRGR4OyYOjSZvThLF1meC9I03WTgR7U5XYIaF3RZQ1ucNefsYuMQpTiwSnIPiqls4L+Nbqj4KfLJieAz9kDw/sphYu/8J+Z4YKZ/Fcpb7dGbPnJjVn/ebIWJlrceGCRspJqQO7PlMOPssHVmWDRorsLXSvS3TWTyjaF9q3uiqEcxsiJ6QP3ZaNCCg0VPFjR6H46pPO7ED77wFw6C1kTCADSA3vGt1CbJFKjch56d386kfJ2mLkqRo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
